### ISSUE TITLE
about the train_val_test.json?

### ISSUE THREAD

**Issue by YeSho-cpp** [hust-linyi/SC-Net#1]
Hello, thank you for your great work, does train_val_test.json have relevant code? Because the original data set does not have this part of the file

**Comment by hust-linyi** [comment]
Hi, thanks for your interest in our work.
This json file save the name list of the train, val, and test sets. For MoNuSeg, we use the official train/test split, and randomly use 6 images in the training set for validation. For CPM, for each type
of tumor, we randomly select one image for validation and two images for testing, thus all the images are divided into 20 images for training, 4 images for validation, and 8 images for testing.
