### ISSUE TITLE
the code of  creatation of  labels_Hcomponent

### ISSUE THREAD

**Issue by liusurufeng** [hust-linyi/SC-Net#4]
Hello, thank you for your great work!
I am trying to use my own datasets to reproduce your work,but I don't find the code of how to generate the **labels_Hcomponent**,otherwise,I don't find how to split the train dataset to two set.

**Comment by hust-linyi** [comment]
Hi, we add the code for generating H component. You can find it [here](https://github.com/hust-linyi/SC-Net/blob/90f2a1cc62310c1799795845e239df74b9564bd4/dataloaders/prepare_data.py#L60).
